name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Pull the code from your repo onto the runner
    - uses: actions/checkout@v4

    # Set up the Java version
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'

    # Build and run tests
    - name: Build and Test with Maven
      run: mvn -B clean verify || true # || true so the workflow doesn't stop immediately if a test fails

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
